name: Gig Graph Data Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git with PAT
        run: |
          git config user.name "gig-graph-bot"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install gspread oauth2client pandas

      
      - name: Process Google Sheet
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python process_sheet.py

      - name: List files
        run: ls -l

      - name: Commit processed data
        run: |
          git config user.name "gig-graph-bot"
          git config user.email "actions@github.com"
          git add data.json output.html
          git commit -m "Gig Graph: Automated data update" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main

